### PR TITLE
feat: get contribute section from README

### PR DESCRIPTION
**Pull request by RichardLitt**
This should grab the Contribute heading and section from the README, if it exists, and use it instead of the fixtures Contribute.

We want to do the same with the license, later - if there is no license file, but there's a section in the README, add the license. Likewise for vice versa. 

Related to #12.

### CODE REVIEW

**Comment by wooorm** [comment]
@RichardLitt So you’re saying that, if there’s no `CONTRIBUTING.md`, we should grab the contents of the section if it’s in the `README.md`, and place it in `CONTRIBUTING.md`?

...and the same for `LICENSE` in the future?

Is there an example of a thing I could use as inspiration, that adds a file if it isn’t already there?

**Comment by RichardLitt** [comment]
Yep! That's exactly what I am saying. We can probably grab the SPDX and fill in the license, too. 

Build a space does this already, adding a file if it isn't there. Look for community checkers - the code _should_ be relatively straightforward to read.

**Comment by wooorm** [comment]
I don’t have access to that, so I couldn’t try it out, but GH-57 should do the trick!

**Comment by RichardLitt** [comment]
What don't you have access to?

**Comment by wooorm** [comment]
Oh sorry this comment went to the wrong issue/pr, it was about the one you mentioned with a Contribute section but no CONTRIBUTE.md file. Never mind!

**Comment by RichardLitt** [comment]
This is superseded by #57. Closing.

**Comment by wooorm** [comment]
Should the branch be deleted?

**Pull request closed without merging**
