### PR TITLE
Add community documentation

### PR DESCRIPTION
**Pull request by wooorm**
Dearest humans,

You are missing some important community files. I am adding them here for you!

Here are some things you should do manually before merging this Pull Request:

- [ ] Check that nothing drastic happened in the `package.json`.
- [ ] Check if .travis.yml was overwritten or not.

Note: This pull request was automatically generated by https://github.com/mntnr/build-a-space. Found an issue? [Let me know!](https://github.com/mntnr/build-a-space/issues)

### CODE REVIEW

**Comment by wooorm** [comment]
Ah, it seems to work!

**Comment by RichardLitt** [comment]
Yep! I've used this on dozens of repos. I keep updating it as needed.

**Comment by RichardLitt** [comment]
Try it on one of your less maintained repos. Should do more.

**Comment by wooorm** [comment]
Sweet, do you have an example repo with a Contribute section, but no `CONTRIBUTING.md` file?

The --branch flag doesn’t work ([branch](https://github.com/mntnr/build-a-space/tree/without-contributing)) as community files come from master apparently.

**Comment by RichardLitt** [comment]
> The --branch flag doesn’t work (branch) as community files come from master apparently.

Hmm. That makes sense. We'll need to reinvent the community api, then. 

Sure: https://github.com/RichardLitt/gh-upstream

**Pull request closed without merging**
